// Vue js/PhoneX/src/admin/AddPostCategory.vue
<template>
  <div class="container mt-5">
    <h1 class="text-center p-3">Post Category</h1>
    <hr />
    <div class="my-5">
      <div class="input-group mb-3">
        <span class="input-group-text">Add Category</span>
        <input
          type="text"
          class="form-control"
          placeholder="Enter Category Name"
          v-model="categoryName"
        />
      </div>
      <button class="btn btn-success w-100" @click="submit" :disabled="loading">
        {{ loading ? "Posting..." : "Post" }}
      </button>
    </div>

    <LoadingSpinner v-if="loading" />
  </div>
</template>

<script>
import { ref } from "vue";
import axios from "axios";
import { useToast } from "vue-toastification";
import LoadingSpinner from "../components/LoadingSpinner.vue";
import Cookies from "js-cookie";

export default {
  components: {
    LoadingSpinner,
  },
  setup() {
    const categoryName = ref(""); // Equivalent to useState("")
    const loading = ref(false);
    const toast = useToast(); // Vue Toastification
    const token = JSON.parse(Cookies.get("AdminId"))?.token;

    const submit = async () => {
      if (!categoryName.value.trim()) {
        toast.error("Please enter a category name");
        return;
      }

      loading.value = true;

      try {
        const response = await axios.post(
          "http://localhost:8080/deviceType/addDeviceType",
          { name: categoryName.value },
          {
            headers: { Authorization: `Bearer ${token}` },
          }
        );

        if (response.status === 202) {
          toast.success("Category added successfully!");
          categoryName.value = ""; // Clear input after success
        } else {
          toast.error(response.data.message || "Failed to add category");
        }
      } catch (error) {
        toast.error(error.response.data || "An error occurred");
      } finally {
        loading.value = false;
      }
    };

    return { categoryName, loading, submit };
  },
};
</script>

<style scoped>
.container {
  max-width: 500px;
  margin: auto;
}
</style>

// Spring/11SpringBootProjectWithJWT/frontend/src/admin/AddPostCategory.jsx
import React from "react";
import axios from "axios";
import { useState } from "react";
import { toast, ToastContainer } from "react-toastify";
import { toastStyle } from "../Constant/general";
import LoadingSpinner from "../componnents/LoadingSpinner";
import cookies from 'js-cookie';

const AddPostCategory = () => {
  const [name, setCategoryName] = useState();
  const [loading, setLoading] = useState(false);
  const {token} = JSON.parse(cookies.get("AdminId"))

  const submit = async () => {
    if (!name) {
      toast.error("Please enter category name", toastStyle);
      return;
    }
    setLoading(true);
    const data = {name}
    try {
      const result = await axios.post("http://localhost:8080/deviceType/addDeviceType", data,{
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      if(result.status ===202){
        toast.success(result.data, toastStyle);
      }else{
        toast.error(result.data.message, toastStyle);
      }
    } catch (error) {
      if(error.response.status){
        toast.error(error.response.data);
      }else{
        toast.error(error.response?.data?.message || error.message, toastStyle);
      }
      
    } finally{
      setLoading(false);
    }
  };
  
  return (
    <>
      <div className="container mt-5">
        <h1 className="text-center p-3">Post Category</h1>
        <hr />
        <div className="my-5">
          <div className="input-group mb-3">
            <span className="input-group-text" id="basic-addon1">
              Add Category
            </span>
            <input
              type="text"
              className="form-control"
              placeholder="Add Category"
              aria-label="Username"
              aria-describedby="basic-addon1"
              value={name}
              onChange={(e) => setCategoryName(e.target.value)}
            />
          </div>
          <button
            type="button"
            className="btn btn-success w-100"
            onClick={submit}
          >
            Post
          </button>
        </div>
      </div>
    
      {loading && <LoadingSpinner />}
    </>
  );
}

export default AddPostCategory;
