// Vue js/PhoneX/src/admin/AdminMiddle.vue
<script setup>
import { ref, onMounted } from "vue";
import cookies from "js-cookie";
import AdminMain from "./AdminMain.vue";
import AdminLogin from "./AdminLogin.vue";

const isLogin = ref(false);

onMounted(() => {
  const id = cookies.get("AdminId");
  isLogin.value = !!id;
});
</script>

<template>
  <div>
    <AdminMain v-if="isLogin" />
    <AdminLogin v-else />
  </div>
</template>

// Spring/11SpringBootProjectWithJWT/frontend/src/admin/AdminMiddle.jsx
import React from 'react'
import cookies from 'js-cookie'
import { useEffect, useState } from 'react';
import AdminMain from './AdminMain';
import AdminLogin from './AdminLogin';

const AdminMiddle = () => {
  const [isLogin, setLogin] = useState(false);

  useEffect(() => {
    const id = cookies.get("AdminId");
    if (id) {
      setLogin(true);
    } else {
      setLogin(false);
    }
  }, []);

  return (
    <div>
      {isLogin ? <AdminMain /> : <AdminLogin />}
    </div>
  );

}

export default AdminMiddle
