// Spring/11SpringBootProjectWithJWT/frontend/src/componnents/Privacypolicy.jsx
import React from "react";

function Privacypolicy() {
  return (
    <>
      <div className="container my-5">
        <p className="text-secondary">Last Updated: 15-March-2024</p>
        Welcome to PhoneX! This Privacy Policy outlines how we collect, use, and
        protect your personal information when you use our mobile website{" "}
        <a
          href="www.phonex.com"
          style={{ textDecoration: "none", color: "red" }}
        >
          www.phonex.com
        </a>{" "}
        and the services offered through the Site.
        <h4 className="my-3">1. Information We Collect</h4>
        <p>
          <b>Personal Information:</b> We may collect personal information such
          as your name, email address, shipping address, and phone number when
          you create an account or make a purchase.
        </p>
        <p>
          <b>Device Information:</b> We automatically collect information about
          your mobile device, including device type, operating system, and
          unique device identifiers.
        </p>
        <p>
          <b>Usage Data:</b> We collect data about how you use the Site,
          including pages visited, time spent on each page, and interactions
          with the Site features.
        </p>
        <h4 className="my-3">2. How We Use Your Information</h4>
        <p>
          <b>We use the information we collect for the following purposes:</b>
          <br />
          Providing and maintaining the Site and Services. <br />
          Processing and fulfilling orders. <br />
          Personalizing your experience on the Site. Analyzing usage trends and
          improving our Site and Services. <br />
          Communicating with you about your account or purchases.
        </p>
        <h4 className="my-3">3. Information Sharing</h4>
        <p>
          <b>
            We may share your personal information with third parties for the
            following purposes:
          </b>
        </p>
        <p>
          <b>1. Service Providers:</b> We may share information with third-party
          service providers who assist us in operating the Site and providing
          the Services.
        </p>
        <p>
          <b>2. Legal Compliance:</b> We may disclose information when required
          by law or in response to valid legal requests.
        </p>
        <p>
          <b>3. Business Transfers:</b> In the event of a merger, acquisition,
          or sale of assets, your information may be transferred as part of the
          transaction.
        </p>
        <h4 className="my-3">4. Data Security</h4>
        <p>
          We implement reasonable security measures to protect your personal
          information from unauthorized access, disclosure, alteration, or
          destruction.
        </p>
        <h4 className="my-3">5. Your Choices</h4>
        You have the rights regarding your personal information: Access, update,
        or delete your information by contacting us. Opt-out of receiving
        marketing communications. Adjust your device settings to control cookies
        and tracking technologies.
        <h4 className="my-3">6. Children's Privacy</h4>
        Our Site and Services are not directed to children under the age of 13.
        We do not knowingly collect personal information from children under 13.
        If you believe we have collected information from a child under 13,
        please contact us.
        <h4 className="my-3">7. Changes to This Policy</h4>
        We may update this Privacy Policy periodically. The updated version will
        be posted on the Site with the effective date. Your continued use of the
        Site after any changes signifies your acceptance of the updated Privacy
        Policy.
      </div>
    </>
  );
}

export default Privacypolicy;

// Vue js/PhoneXwithVueX/src/pages/PrivacyPolicy.vue
<template>
  <div class="container my-5">
    <p class="text-secondary">Last Updated: 15-March-2024</p>
    Welcome to PhoneX! This Privacy Policy outlines how we collect, use, and
    protect your personal information when you use our mobile website
    <a href="www.phonex.com" style="text-decoration: none; color: red">
      www.phonex.com
    </a>
    and the services offered through the Site.

    <h4 class="my-3">1. Information We Collect</h4>
    <p>
      <b>Personal Information:</b> We may collect personal information such as
      your name, email address, shipping address, and phone number when you
      create an account or make a purchase.
    </p>
    <p>
      <b>Device Information:</b> We automatically collect information about your
      mobile device, including device type, operating system, and unique device
      identifiers.
    </p>
    <p>
      <b>Usage Data:</b> We collect data about how you use the Site, including
      pages visited, time spent on each page, and interactions with the Site
      features.
    </p>

    <h4 class="my-3">2. How We Use Your Information</h4>
    <p>
      <b>We use the information we collect for the following purposes:</b>
      <br />
      Providing and maintaining the Site and Services. <br />
      Processing and fulfilling orders. <br />
      Personalizing your experience on the Site. <br />
      Analyzing usage trends and improving our Site and Services. <br />
      Communicating with you about your account or purchases.
    </p>

    <h4 class="my-3">3. Information Sharing</h4>
    <p>
      <b>
        We may share your personal information with third parties for the
        following purposes:
      </b>
    </p>
    <p>
      <b>1. Service Providers:</b> We may share information with third-party
      service providers who assist us in operating the Site and providing the
      Services.
    </p>
    <p>
      <b>2. Legal Compliance:</b> We may disclose information when required by
      law or in response to valid legal requests.
    </p>
    <p>
      <b>3. Business Transfers:</b> In the event of a merger, acquisition, or
      sale of assets, your information may be transferred as part of the
      transaction.
    </p>

    <h4 class="my-3">4. Data Security</h4>
    <p>
      We implement reasonable security measures to protect your personal
      information from unauthorized access, disclosure, alteration, or
      destruction.
    </p>

    <h4 class="my-3">5. Your Choices</h4>
    <p>
      You have the rights regarding your personal information:
      <br />
      Access, update, or delete your information by contacting us.
      <br />
      Opt-out of receiving marketing communications.
      <br />
      Adjust your device settings to control cookies and tracking technologies.
    </p>

    <h4 class="my-3">6. Children's Privacy</h4>
    <p>
      Our Site and Services are not directed to children under the age of 13. We
      do not knowingly collect personal information from children under 13. If
      you believe we have collected information from a child under 13, please
      contact us.
    </p>

    <h4 class="my-3">7. Changes to This Policy</h4>
    <p>
      We may update this Privacy Policy periodically. The updated version will
      be posted on the Site with the effective date. Your continued use of the
      Site after any changes signifies your acceptance of the updated Privacy
      Policy.
    </p>
  </div>
</template>
