// Spring/11SpringBootProjectWithJWT/frontend/src/componnents/Return.jsx
import React from "react";

function Return() {
  return (
    <div className="container my-5">
      <h1 className="text-center my-4">Return Policy</h1>
      <p>
        We want you to be completely satisfied with your purchase of a gadget
        from us. If you have any concerns or issues with your gadget, please
        review our return policy below.
      </p>
      <hr />
      <h3>1. Return Period:</h3>
      You may return your device within 14 days of the original purchase date.
      <hr />
      <h3>2. Eligibility Criteria for Returns:</h3>
      <p>
        The device must be in its original condition with all accessories,
        manuals, and packaging included. The device must not have any physical
        or water damage. The device must not have been rooted, modified, or
        tampered with in any way.
      </p>
      <hr />
      <h3>3. Return Process:</h3>
      <p>
        To initiate a return, please contact our customer service team at{" "}
        <a
          href="mailto:phonex@gmail.com"
          style={{ textDecoration: "none", color: "red" }}
        >
          PhoneX@gmail.com.
        </a>
        . They will provide you with a return authorization and instructions on
        how to return the device.
      </p>
      <hr />
      <h3>4. Refund or Exchange:</h3>
      <p>
        Upon receiving and inspecting the returned device, we will process your
        refund or exchange based on the condition of the device and the reason
        for the return. If the device is eligible for a refund, we will refund
        the purchase amount to your original payment method. If you prefer an
        exchange, we will work with you to find a suitable replacement.
      </p>
      <hr />
      <h3>5. Exceptions:</h3>
      <p>
        Please note that certain conditions may void or limit your eligibility
        for a return or refund, such as: Damage caused by misuse, accidents, or
        neglect. Unauthorized repairs or modifications to the device. Missing or
        damaged accessories or packaging.
      </p>
      <hr />
      <h3>6. Warranty:</h3>
      <p>
        Your device may be covered by a manufacturer's warranty. Please refer to
        the warranty terms and conditions provided with your device for more
        information.
      </p>
      <hr />
      <h3>7. Contact Us:</h3>
      <p>
        If you have any questions or need assistance with your return, please
        don't hesitate to contact our customer service team at{" "}
        <a
          href="mailto:phonex@gmail.com"
          style={{ textDecoration: "none", color: "red" }}
        >
          PhoneX@gmail.com.
        </a>
        .
      </p>
    </div>
  );
}

export default Return;

// Vue js/PhoneXwithVueX/src/pages/Return.vue
<script setup></script>

<template>
  <div class="container my-5">
    <h1 class="text-center my-4">Return Policy</h1>
    <p>
      We want you to be completely satisfied with your purchase of a gadget from
      us. If you have any concerns or issues with your gadget, please review our
      return policy below.
    </p>
    <hr />

    <h3>1. Return Period:</h3>
    <p>
      You may return your device within 14 days of the original purchase date.
    </p>
    <hr />

    <h3>2. Eligibility Criteria for Returns:</h3>
    <p>
      The device must be in its original condition with all accessories,
      manuals, and packaging included. The device must not have any physical or
      water damage. The device must not have been rooted, modified, or tampered
      with in any way.
    </p>
    <hr />

    <h3>3. Return Process:</h3>
    <p>
      To initiate a return, please contact our customer service team at
      <a
        href="mailto:phonex@gmail.com"
        style="text-decoration: none; color: red"
      >
        PhoneX@gmail.com </a
      >. They will provide you with a return authorization and instructions on
      how to return the device.
    </p>
    <hr />

    <h3>4. Refund or Exchange:</h3>
    <p>
      Upon receiving and inspecting the returned device, we will process your
      refund or exchange based on the condition of the device and the reason for
      the return. If the device is eligible for a refund, we will refund the
      purchase amount to your original payment method. If you prefer an
      exchange, we will work with you to find a suitable replacement.
    </p>
    <hr />

    <h3>5. Exceptions:</h3>
    <p>
      Please note that certain conditions may void or limit your eligibility for
      a return or refund, such as: Damage caused by misuse, accidents, or
      neglect. Unauthorized repairs or modifications to the device. Missing or
      damaged accessories or packaging.
    </p>
    <hr />

    <h3>6. Warranty:</h3>
    <p>
      Your device may be covered by a manufacturer's warranty. Please refer to
      the warranty terms and conditions provided with your device for more
      information.
    </p>
    <hr />

    <h3>7. Contact Us:</h3>
    <p>
      If you have any questions or need assistance with your return, please
      don't hesitate to contact our customer service team at
      <a
        href="mailto:phonex@gmail.com"
        style="text-decoration: none; color: red"
      >
        PhoneX@gmail.com </a
      >.
    </p>
  </div>
</template>

<style scoped>
/* Add custom styles if needed */
</style>
