// Spring/11SpringBootProjectWithJWT/frontend/src/componnents/SignUp.jsx
import React from "react";
import Style from "../CSS/SignUp.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { useNavigate } from "react-router-dom";
import { useState } from "react";
import axios from "axios";
import { toast, ToastContainer } from "react-toastify";
import { toastStyle } from "../Constant/general";
import LoadingSpinner from "./LoadingSpinner";

function SignUp() {
  const [username, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [gender, setGender] = useState("");
  const [loading,setLoading] = useState(false);
  const [age,setAge] = useState("");
  const [address,setAddress] = useState("");
  const [contactNo,setContactNo] = useState("");
  const role="CUSTOMER";

  const reg = async (e) => {
    e.preventDefault();

    if (
      username &&
      email &&
      password &&
      confirmPassword &&
      gender &&
      password === confirmPassword &&
      age &&
      address &&
      contactNo
    ) {
      try{
        setLoading(true);
        const data = { username, email, password,gender,age,contactNo,address,role };
        const response = await axios
        .post("http://localhost:8080/customer/register", data)
          if (response.status === 201) {
            toast.success(response.data,toastStyle);
            setTimeout(()=>{navigate("/SignIn#top");},1500)
          } else {
            toast.error(response.message);
          }
      }
      catch(error){
        if (error.response) {
          if (error.response.status) {
              toast.error(error.response.data || error.response.data.message, toastStyle);
          } else {
              toast.error(error.message, toastStyle);
          }
      } else {
          toast.error("An error occurred. Please try again later.", toastStyle);
      }
      }
      finally{
        setLoading(false);
      }
    } else {
      toast.error("Please fill in all the fields and ensure the passwords match.",toastStyle);
    }
  };
  const navigate = useNavigate("");
  React.useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <div className={Style.hero} id="top">
        <div className="container py-5">
          <div className="col-md-6">
            <h2 className="text-center text-white"> Sign Up</h2>
            <form className="row g-3 text-start">
              <div className="col-12">
                <input
                  type="text"
                  value={username}
                  className="form-control"
                  placeholder="Name"
                  aria-label="name"
                  onChange={(e) => setName(e.target.value)}
                />
              </div>
              <div className="col-12">
                <input
                  type="email"
                  value={email}
                  className="form-control"
                  id="inputEmail4"
                  placeholder="Email"
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <div className="col-12">
                <input
                  type="password"
                  value={password}
                  className="form-control"
                  id="inputPassword4"
                  placeholder="Password"
                  onChange={(e) => setPassword(e.target.value)}
                />
              </div>
              <div className="col-12">
                <input
                  type="confirmPassword"
                  value={confirmPassword}
                  className="form-control"
                  id="inputPassword4"
                  placeholder="Confirm Password"
                  onChange={(e) => setConfirmPassword(e.target.value)}
                />
              </div>
              
              <div className="col-12">
                <input
                  type="number"
                  value={age}
                  className="form-control"
                  placeholder="Age"
                  aria-label="age"
                  onChange={(e) => setAge(e.target.value)}
                />
              </div>
              <div className="col-12">
                <input
                  type="number"
                  value={contactNo}
                  className="form-control"
                  placeholder="Contact No"
                  aria-label="Contact No"
                  onChange={(e) => setContactNo(e.target.value)}
                />
              </div>
              <div className="col-12">
                <input
                  type="textarea"
                  value={address}
                  className="form-control"
                  placeholder="Address"
                  aria-label="textArea"
                  onChange={(e) => setAddress(e.target.value)}
                />
              </div>
              <div className="my-3 mx-1 col-12">
                <div className={`${Style.radio} form-check`}>
                  <input
                    value="Male"
                    className="form-check-input"
                    type="radio"
                    name="flexRadioDefault"
                    id="flexRadioDefault2"
                    onChange={(e) => setGender(e.target.value)}
                  />
                  <label className="form-check-label" for="flexRadioDefault2">
                    Male
                  </label>
                </div>
                <div className={`${Style.radio} form-check`}>
                  <input
                    value="Female"
                    className="form-check-input"
                    type="radio"
                    name="flexRadioDefault"
                    id="flexRadioDefault3"
                    onChange={(e) => setGender(e.target.value)}
                  />
                  <label className="form-check-label " for="flexRadioDefault3">
                    Female
                  </label>
                </div>
                <div className={`${Style.radio} form-check`}>
                  <input
                    value="Other"
                    className="form-check-input"
                    type="radio"
                    name="flexRadioDefault"
                    id="flexRadioDefault4"
                    onChange={(e) => setGender(e.target.value)}
                  />
                  <label className="form-check-label" for="flexRadioDefault4">
                    Other
                  </label>
                </div>
              </div>
              <div className="col-12">
                <button
                  type="submit"
                  className="btn btn-success col-12"
                  onClick={reg}
                >
                  Sign up
                </button>
              </div>
              <div className="text-white">
                Already Have an Account?{" "}
                <span
                  className={Style.signin}
                  onClick={() => navigate("/SignIn#top")}
                >
                  SignIn
                </span>
              </div>
            </form>
          </div>
        </div>
      </div>
      {loading && <LoadingSpinner />}
      
    </>
  );
}

export default SignUp;

// Vue js/PhoneXwithVueX/src/pages/SignUp.vue
<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import { toast } from "vue3-toastify";
import LoadingSpinner from "../components/LoadingSpinner.vue";
import { registerCustomer } from "../services/apis";

const router = useRouter();
const username = ref("");
const email = ref("");
const password = ref("");
const confirmPassword = ref("");
const gender = ref("");
const age = ref("");
const address = ref("");
const contactNo = ref("");
const loading = ref(false);
const role = "CUSTOMER";

const reg = async (e) => {
  e.preventDefault();

  if (
    username.value &&
    email.value &&
    password.value &&
    confirmPassword.value &&
    gender.value &&
    password.value === confirmPassword.value &&
    age.value &&
    address.value &&
    contactNo.value
  ) {
    try {
      loading.value = true;
      const userData = {
        username: username.value,
        email: email.value,
        password: password.value,
        gender: gender.value,
        age: age.value,
        contactNo: contactNo.value,
        address: address.value,
        role,
      };

      const response = await registerCustomer(userData);

      if (response.status === 201) {
        toast.success(response.data);
        setTimeout(() => {
          router.push("/SignIn#top");
        }, 1500);
      } else {
        toast.error(response.data.message);
      }
    } catch (error) {
      toast.error(error);
    } finally {
      loading.value = false;
    }
  } else {
    toast.error("Please fill in all fields and ensure passwords match.");
  }
};
</script>

<template>
  <div class="hero" id="top">
    <div class="container py-5">
      <div class="col-md-6">
        <h2 class="text-center text-white">Sign Up</h2>
        <form class="row g-3 text-start" @submit="reg">
          <div class="col-12">
            <input
              type="text"
              v-model="username"
              class="form-control"
              placeholder="Name"
            />
          </div>
          <div class="col-12">
            <input
              type="email"
              v-model="email"
              class="form-control"
              placeholder="Email"
            />
          </div>
          <div class="col-12">
            <input
              type="password"
              v-model="password"
              class="form-control"
              placeholder="Password"
            />
          </div>
          <div class="col-12">
            <input
              type="password"
              v-model="confirmPassword"
              class="form-control"
              placeholder="Confirm Password"
            />
          </div>
          <div class="col-12">
            <input
              type="number"
              v-model="age"
              class="form-control"
              placeholder="Age"
            />
          </div>
          <div class="col-12">
            <input
              type="number"
              v-model="contactNo"
              class="form-control"
              placeholder="Contact No"
            />
          </div>
          <div class="col-12">
            <input
              type="text"
              v-model="address"
              class="form-control"
              placeholder="Address"
            />
          </div>
          <div class="my-3 mx-1 col-12">
            <div class="radio form-check">
              <input
                v-model="gender"
                value="Male"
                class="form-check-input"
                type="radio"
                name="gender"
              />
              <label class="form-check-label">Male</label>
            </div>
            <div class="radio form-check">
              <input
                v-model="gender"
                value="Female"
                class="form-check-input"
                type="radio"
                name="gender"
              />
              <label class="form-check-label">Female</label>
            </div>
            <div class="radio form-check">
              <input
                v-model="gender"
                value="Other"
                class="form-check-input"
                type="radio"
                name="gender"
              />
              <label class="form-check-label">Other</label>
            </div>
          </div>
          <div class="col-12">
            <button type="submit" class="btn btn-success col-12">
              Sign Up
            </button>
          </div>
          <div class="text-white">
            Already Have an Account?
            <span class="signin" @click="router.push('/SignIn#top')"
              >Sign In</span
            >
          </div>
        </form>
      </div>
    </div>
  </div>

  <LoadingSpinner v-if="loading" />
</template>

<style scoped>
@import "../CSS/SignUp.module.css";
</style>
