// Spring/11SpringBootProjectWithJWT/frontend/src/componnents/EmptyBagItem.jsx
import React from "react";
import { useNavigate } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";

const EmptyBagItem = () => {
  const navigate = useNavigate();
  React.useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <div className="container d-flex flex-column align-items-center justify-content-center mt-5 text-center">
      <img
        src="../../public/assets/background/pato-juan.gif" 
        alt="Empty Bag"
        className="mb-4"
        style={{ maxWidth: "150px" }}
      />
      <h2 className="mb-3">Your Bag is Empty 😢</h2>
      <p className="mb-4 text-muted">
        Looks like you haven’t added anything to your bag yet.
      </p>
      <button
        className="btn btn-danger px-4 py-2"
        onClick={()=> navigate('/')}
      >
        Go to Shopping
      </button>
    </div>
  );
};

export default EmptyBagItem;

// Vue js/PhoneXwithVueX/src/components/EmptyBagItem.vue
<script setup>
import { useRouter } from "vue-router";

const router = useRouter();
</script>

<template>
  <div
    class="container d-flex flex-column align-items-center justify-content-center mt-5 text-center"
  >
    <img
      src="../assets/background/pato-juan.gif"
      alt="Empty Bag"
      class="mb-4"
      style="max-width: 150px"
    />
    <h2 class="mb-3">Your Bag is Empty 😢</h2>
    <p class="mb-4 text-muted">
      Looks like you haven’t added anything to your bag yet.
    </p>

    <button class="btn btn-danger px-4 py-2" @click="router.push('/')">
      Go to Shopping
    </button>
  </div>
</template>

<style scoped>
/* Add any required styles */
</style>
