// Spring/11SpringBootProjectWithJWT/frontend/src/componnents/LoadingSpinner.jsx
import Styles from "../CSS/Loading.module.css"
const LoadingSpinner = ()=> {
  return (
    <>
      <div className={`${Styles["spinner-main"]} spinner animate__animated animate__fadeIn animate__fast text-center`}>
        <div class="spinner-grow text-success" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <div class="spinner-grow text-danger" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
    </>
  );
}

export default LoadingSpinner;

// Vue js/PhoneX/src/components/LoadingSpinner.vue
<template>
  <div
    class="spinner-main spinner animate__animated animate__fadeIn animate__fast text-center"
  >
    <div class="spinner-grow text-success" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-danger" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</template>

<style setup>
@import "../CSS/Loading.module.css";
</style>
