// Vue js/PhoneXwithVueX/src/components/EditUser.vue
<script setup>
import { ref } from "vue";
import axios from "axios";
import { toast } from "vue3-toastify";
import cookies from "js-cookie";
import LoadingSpinner from "./LoadingSpinner.vue"; // Import spinner component

const oldPassword = ref("");
const newPassword = ref("");
const confirmNewPassword = ref("");
const loading = ref(false);

const userCookie = cookies.get("UserCookie");
const token = userCookie ? JSON.parse(userCookie).token : null;
const id = userCookie ? JSON.parse(userCookie).id : null;
const gender = userCookie ? JSON.parse(userCookie).gender : null;

// Update password function
const updatePassword = async () => {
  if (!oldPassword.value || !newPassword.value || !confirmNewPassword.value) {
    toast.error("Please fill all the details");
    return;
  }
  if (newPassword.value !== confirmNewPassword.value) {
    toast.error("New password and confirm password must be the same");
    return;
  }

  const data = {
    id,
    oldPassword: oldPassword.value,
    newPassword: newPassword.value,
  };

  try {
    loading.value = true;
    const response = await axios.patch(
      "http://localhost:8080/customer/changePassword",
      data,
      {
        headers: { Authorization: `Bearer ${token}` },
      }
    );

    if (response.status === 200) {
      toast.success(response.data);
    } else {
      toast.error(response.data.message);
    }
  } catch (error) {
    toast.error(error.response?.data || error.message);
  } finally {
    loading.value = false;
  }
};
</script>

<template>
  <div class="card text-center container my-5">
    <div class="card-header">Edit User Detail</div>
    <div class="card-body">
      <p class="card-text">Change Account Details</p>

      <!-- Avatar Selection Based on Gender -->
      <p style="font-size: '3rem'">
        <img
          v-if="gender === 'Male'"
          src="../assets/background/manavtar.png"
          style="width: 10rem; border-radius: 50%"
          class="card-img-top"
          alt="avatar"
        />
        <img
          v-else-if="gender === 'Female'"
          src="../assets/background/womenavtar.jpg"
          style="width: 10rem; border-radius: 50%"
          class="card-img-top"
          alt="avatar"
        />
        <FcDecision v-else />
      </p>

      <!-- Password Inputs -->
      <div class="input-group mb-3">
        <span class="input-group-text">Old Password</span>
        <input
          type="password"
          class="form-control"
          v-model="oldPassword"
          placeholder="Old Password"
        />
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text">New Password</span>
        <input
          type="password"
          class="form-control"
          v-model="newPassword"
          placeholder="New Password"
        />
      </div>

      <div class="input-group mb-3">
        <span class="input-group-text">Confirm Password</span>
        <input
          type="password"
          class="form-control"
          v-model="confirmNewPassword"
          placeholder="Confirm New Password"
        />
      </div>

      <!-- Update Button -->
      <button class="btn btn-info w-100 text-white" @click="updatePassword">
        Update
      </button>
    </div>
  </div>

  <!-- Loading Spinner -->
  <LoadingSpinner v-if="loading" />
</template>

<style scoped>
/* Add any required styles */
</style>

// Spring/11SpringBootProjectWithJWT/frontend/src/componnents/EditUser.jsx
import React, { useEffect } from "react";
import cookies from "js-cookie";
import axios from "axios";
import { useState } from "react";
import { FcDecision } from "react-icons/fc";
import manavtar from "../../public/assets/background/manavtar.png";
import womenavtar from "../../public/assets/background/womenavtar.jpg";
import { toast } from "react-toastify";
import { toastStyle } from "../Constant/general";
import LoadingSpinner from "./LoadingSpinner";

const EditUser = () => {
  const [oldPassword, setOldPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmNewPassword, setConfirmNewPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const userCookie = cookies.get("UserCookie");
  const token = userCookie ? JSON.parse(userCookie).token : null;
  const id = userCookie?JSON.parse(userCookie).id:null;
  const gender = userCookie?JSON.parse(userCookie).gender:null;

  

  const update = async () => {
    if (oldPassword && newPassword && confirmNewPassword) {
      const data = { id, oldPassword, newPassword };
      try {
        setLoading(true);
        const response = await axios.patch(
          "http://localhost:8080/customer/changePassword",
          data,{
            headers: {
              Authorization: `Bearer ${token}`,
            }
          }
        );
        if (response.status === 200) {
          toast.success(response.data, toastStyle);
        } else {
          toast.error(response.data.message, toastStyle);
        }
      } catch (error) {
        if(error.response){
          toast.error(error.response.data||error.message , toastStyle);
        }else{
          toast.error(error.message, toastStyle);
        }
      } finally {
        setLoading(false);
      }
    } else {
      toast.error("Please fill all the Details", toastStyle);
    }
  };

  return (
    <>
      <div class="card text-center container my-5">
        <div class="card-header">Edit User Detail</div>
        <div class="card-body">
          <p class="card-text">Change Account Details</p>
          <p style={{ width: "", fontSize: "3rem" }}>
            {gender === "Male" ? (
              <img
                src={manavtar}
                style={{ width: "10rem", borderRadius: "50%" }}
                class="card-img-top"
                alt="avtar"
              />
            ) : gender === "Female" ? (
              <img
                src={womenavtar}
                style={{ width: "10rem", borderRadius: "50%" }}
                class="card-img-top"
                alt="avtar"
              />
            ) : (
              <FcDecision />
            )}
          </p>
          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">
              Old Password
            </span>
            <input
              type="password"
              class="form-control"
              placeholder={`Old Password`}
              value={oldPassword}
              onChange={(e) => setOldPassword(e.target.value)}
              aria-label="Username"
              aria-describedby="basic-addon1"
            />
          </div>
          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">
              New Password
            </span>
            <input
              type="password"
              class="form-control"
              placeholder={`New Password`}
              value={newPassword}
              onChange={(e) => setNewPassword(e.target.value)}
              aria-label="Username"
              aria-describedby="basic-addon1"
            />
          </div>
          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">
              Confirm Password
            </span>
            <input
              type="password"
              class="form-control"
              placeholder={`Confirm New Password`}
              value={confirmNewPassword}
              onChange={(e) => setConfirmNewPassword(e.target.value)}
              aria-label="Username"
              aria-describedby="basic-addon1"
            />
          </div>
          <button
            className="btn btn-info w-100 text-white"
            type="button"
            onClick={update}
          >
            Update
          </button>
        </div>
      </div>
      {loading && <LoadingSpinner />}
    </>
  );
};

export default EditUser;
