// Vue js/PhoneX/src/components/Footer.vue
<script setup>
import { useRouter } from "vue-router";

const router = useRouter();

const navigate = (path) => {
  router.push(path);
};
</script>

<template>
  <footer class="footer py-5 row">
    <div class="col-sm-12 col-md-3 px-2 mt-4">
      <h4>About</h4>
      <p class="text-secondary">
        We PhoneX Developer provide you best mobile phones and accessories based
        on your needs. Thank you for visiting our website.
      </p>
    </div>

    <div class="contact col-sm-12 col-md-3 px-2 mt-4">
      <h4>Contact</h4>
      <a
        href="https://maps.app.goo.gl/jouiWzjKgNDnKSAo6"
        target="_blank"
        class="text-secondary"
      >
        <i class="pi pi-location" style="color: red; font-size: 1rem"></i>
        &nbsp; Gota, Ahmedabad-382481
      </a>
      <a href="tel:+919974177873" class="text-secondary">
        <i class="pi pi-location" style="color: red; font-size: 1rem"></i>
        &nbsp; Phone: +91 9974177873
      </a>
      <a href="mailto:phonex@gmail.com" class="text-secondary">
        <i class="pi pi-location" style="color: red; font-size: 1rem"></i>
        &nbsp; Email: phonex@gmail.com
      </a>
    </div>

    <div class="contact col-sm-12 col-md-3 px-2 mt-4">
      <h4>Categories</h4>
      <a href="#" class="text-secondary">Phones</a>
      <a href="#" class="text-secondary">Headphones</a>
      <a href="#" class="text-secondary">Airpods</a>
      <a href="#" class="text-secondary">AR-VR</a>
    </div>

    <div class="contact col-sm-12 col-md-3 px-2 mt-4">
      <h4>Pages</h4>
      <button class="btn btn-link text-secondary" @click="navigate('/')">
        Home
      </button>
      <button
        class="btn btn-link text-secondary"
        @click="navigate('/About#top')"
      >
        About
      </button>
      <button
        class="btn btn-link text-secondary"
        @click="navigate('/Privacypolicy#top')"
      >
        Privacy Policy
      </button>
      <button
        class="btn btn-link text-secondary"
        @click="navigate('/Return#top')"
      >
        Returns
      </button>
      <button
        class="btn btn-link text-secondary"
        @click="navigate('/Term#top')"
      >
        Terms & Conditions
      </button>
    </div>
  </footer>

  <hr />

  <div class="payment px-3">
    <div class="logo">
      <a class="text-start text-secondary fs-5" href="#">
        Phone<span style="color: red">X</span>
      </a>
    </div>
    <div class="paymentcards">
      <a href="#">
        <img src="../assets/Payment/visa.png" alt="Visa Payment" />
      </a>
      <a href="#">
        <img src="../assets/Payment/mastercard.png" alt="MasterCard Payment" />
      </a>
      <a href="#">
        <img src="../assets/Payment/paypal.png" alt="PayPal Payment" />
      </a>
      <a href="#">
        <img src="../assets/Payment/Maestro.png" alt="Maestro Payment" />
      </a>
      <a href="#">
        <img
          src="../assets/Payment/visa elecron.png"
          alt="Visa Electron Payment"
        />
      </a>
    </div>
  </div>
</template>

<style scoped>
@import "../CSS//Footer.module.css";
</style>

// Spring/11SpringBootProjectWithJWT/frontend/src/componnents/Footer.jsx
import React from "react";
import Style from "../CSS/Footer.module.css";
import { FaPaperPlane } from "react-icons/fa";
import { MdAttachEmail } from "react-icons/md";
import { IoPhonePortraitOutline } from "react-icons/io5";
import { useNavigate } from "react-router-dom";
function Footer() {
  const navigate = useNavigate();
  return (
    <>
      <div className={`${Style.footer} py-5 row`}>
        <div className="col-sm-12 col-md-3 px-2 mt-4">
          <h4>About</h4>
          <p className="text-secondary">
            We PhoneX Developer provide you best mobile phone and it's
            accessories based on your need. Thank you for visiting our website
          </p>
        </div>

        <div className={`${Style.contact} col-sm-12 col-md-3 px-2 mt-4`}>
          <h4>Contact</h4>
          <a
            href="https://maps.app.goo.gl/jouiWzjKgNDnKSAo6"
            target="_blank"
            className="text-secondary"
          >
            <FaPaperPlane /> &nbsp;Gota, Ahmedabad-382481
          </a>
          <a
            href="callto:9974177873"
            target="_blank"
            className="text-secondary"
          >
            <IoPhonePortraitOutline /> &nbsp;Phone: +91 9974177873
          </a>
          <a
            href="mailto:phonex@gmail.com"
            target="_blank"
            className="text-secondary"
          >
            <MdAttachEmail /> &nbsp;Email: phonex@gmail.com
          </a>
        </div>

        <div className={`${Style.contact} col-sm-12 col-md-3 px-2 mt-4`}>
          <h4>Categories</h4>
          <a href="#" className="text-secondary">
            Phones
          </a>
          <a href="#" className="text-secondary">
            Headphones
          </a>
          <a href="#" className="text-secondary">
            Airpodes
          </a>
          <a href="#" className="text-secondary">
            AR-VR
          </a>
        </div>

        <div className={`${Style.contact} col-sm-12 col-md-3 px-2 mt-4`}>
          <h4>Pages</h4>
          <a href="#" className="text-secondary" onClick={() => navigate("/")}>
            Home
          </a>
          <a
            href="#"
            className="text-secondary"
            onClick={() => navigate("/About#top")}
          >
            About
          </a>
          <a
            href="#"
            className="text-secondary"
            onClick={() => navigate("/Privacypolicy#top")}
          >
            Privacy Policy
          </a>
          <a
            href="#"
            className="text-secondary"
            onClick={() => navigate("/Return#top")}
          >
            Returns
          </a>
          <a
            href="#"
            className="text-secondary"
            onClick={() => navigate("/Term#top")}
          >
            Terms & Conditions
          </a>
        </div>
      </div>
      <hr />
      <div className={`${Style.payment} px-3`}>
        <div className={Style.logo}>
          <a className={`text-start text-secondary fs-5`} href="#">
            Phone
            <span style={{ color: "red" }}>X</span>
          </a>
        </div>
        <div className={Style.paymentcards}>
          <a href="#">
            <img src="/assets/Payment/visa.png" alt="payment" title="visa" />
          </a>
          <a href="#">
            <img
              src="/assets/Payment/mastercard.png"
              alt="payment"
              title="visa"
            />
          </a>
          <a href="#">
            <img src="/assets/Payment/paypal.png" alt="payment" title="visa" />
          </a>
          <a href="#">
            <img src="/assets/Payment/Maestro.png" alt="payment" title="visa" />
          </a>
          <a href="#">
            <img
              src="/assets/Payment/visa elecron.png"
              alt="payment"
              title="visa"
            />
          </a>
        </div>
      </div>
    </>
  );
}

export default Footer;
